framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true
        # Define only once here
        cookie_lifetime: 604800   # Session cookie expires after week seconds
        name: 'app_session'
        cookie_path: '/'
        cookie_domain: '127.0.0.1'
        cookie_secure: false
        cookie_httponly: true
        cookie_samesite: 'lax'

    # Additional session or other settings
